server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: http://gitlab.shequyouwo.com/yanshuai/config-repo.git
          search-paths: config
          username: yanshuai@shangweiec.com
          password: ******

